apiVersion: v1
kind: Service
metadata:
  name: flask-devops-lab-service
spec:
  type: NodePort
  selector:
    app: flask-devops-lab
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
